// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    AddUserModal: typeof import('./src/components/AddUserModal/index.vue')['default']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    AntBreadcrumb: typeof import('./src/components/AntBreadcrumb/index.vue')['default']
    AntDatePicker: typeof import('./src/components/AntDatePicker/AntDatePicker.vue')['default']
    AntModalUpdate: typeof import('./src/components/AntModalUpdate/AntModalUpdate.vue')['default']
    AntSelect: typeof import('./src/components/AntSelect/AntSelect.vue')['default']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ConfirmSelectBtn: typeof import('./src/components/ConfirmSelectBtn/index.vue')['default']
    FileSelector: typeof import('./src/components/FileSelector/FileSelector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelfInput: typeof import('./src/components/SelfInput/SelfInput.vue')['default']
    SelfPagination: typeof import('./src/components/SelfPagination/SelfPagination.vue')['default']
    SelfSearch: typeof import('./src/components/SelfSearch/index.vue')['default']
    SelfTitle: typeof import('./src/components/SelfTitle/SelfTitle.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/SvgIcon.vue')['default']
    UserInfo: typeof import('./src/components/UserInfo/UserInfo.vue')['default']
  }
}
